import { EpubDocument } from '@/services/epub/epubParser';
import { extractPdfMetadata } from '@/services/pdf/pdfMetadata';
import { extractSections } from '@/services/reader/ReflowableDocument';
import { TxtDocument } from '@/services/txt/txtDocument';
import type { BookFormat, TextSection } from '@/types/models';
import { decodeText } from '@/utils/text';

/** Metadata and content extracted from a book file during import. */
export interface ExtractedBook {
  title: string | null;
  authors: string[];
  language: string | null;
  description: string | null;
  publisher: string | null;
  cover: { bytes: Uint8Array; extension: string } | null;
  totalPages: number | null;
  totalChapters: number | null;
  /** Text to index for search. `null` = indexed later (PDF: when first opened). */
  sections: TextSection[] | null;
}

export interface BookFormatHandler {
  format: BookFormat;
  /** File extension used when storing the book. */
  extension: string;
  extract(bytes: Uint8Array, fileName: string): Promise<ExtractedBook>;
}

const epubHandler: BookFormatHandler = {
  format: 'epub',
  extension: 'epub',
  async extract(bytes) {
    const doc = await EpubDocument.open(bytes);
    const cover = await doc.getCover();
    return {
      title: doc.metadata.title,
      authors: doc.metadata.authors,
      language: doc.metadata.language,
      description: doc.metadata.description,
      publisher: doc.metadata.publisher,
      cover: cover ? { bytes: cover.bytes, extension: cover.extension } : null,
      totalPages: null,
      totalChapters: doc.chapters.length,
      sections: await extractSections(doc),
    };
  },
};

const pdfHandler: BookFormatHandler = {
  format: 'pdf',
  extension: 'pdf',
  async extract(bytes) {
    const meta = extractPdfMetadata(bytes);
    return {
      title: meta.title,
      authors: meta.author ? [meta.author] : [],
      language: null,
      description: null,
      publisher: null,
      cover: null, // generated by the reader (first page thumbnail)
      totalPages: meta.pageCount,
      totalChapters: null,
      sections: null,
    };
  },
};

const txtHandler: BookFormatHandler = {
  format: 'txt',
  extension: 'txt',
  async extract(bytes) {
    const text = decodeText(bytes);
    const doc = new TxtDocument(text);
    return {
      title: TxtDocument.guessTitle(text),
      authors: [],
      language: null,
      description: null,
      publisher: null,
      cover: null,
      totalPages: null,
      totalChapters: doc.chapters.length,
      sections: await extractSections(doc),
    };
  },
};

/**
 * Registry of format handlers. To support a new format (e.g. CBZ) add its
 * {@link BookFormatHandler} here, extend `BookFormat` and `SUPPORTED_FORMATS`,
 * and provide a reader component.
 */
export const FORMAT_HANDLERS: Record<BookFormat, BookFormatHandler> = {
  epub: epubHandler,
  pdf: pdfHandler,
  txt: txtHandler,
};
